// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: evo/execution.proto

#include "evo/execution.pb.h"
#include "evo/execution.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace evo {
namespace execution {
namespace v1 {

static const char* ControlService_method_names[] = {
  "/evo.execution.v1.ControlService/SubmitRun",
  "/evo.execution.v1.ControlService/CancelRun",
  "/evo.execution.v1.ControlService/GetRun",
  "/evo.execution.v1.ControlService/Health",
};

std::unique_ptr< ControlService::Stub> ControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ControlService::Stub> stub(new ControlService::Stub(channel, options));
  return stub;
}

ControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubmitRun_(ControlService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelRun_(ControlService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRun_(ControlService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Health_(ControlService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ControlService::Stub::SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::evo::execution::v1::SubmitRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitRun_, context, request, response);
}

void ControlService::Stub::async::SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitRun_, context, request, response, std::move(f));
}

void ControlService::Stub::async::SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>* ControlService::Stub::PrepareAsyncSubmitRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::evo::execution::v1::SubmitRunResponse, ::evo::execution::v1::SubmitRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>* ControlService::Stub::AsyncSubmitRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlService::Stub::CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::evo::execution::v1::CancelRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelRun_, context, request, response);
}

void ControlService::Stub::async::CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelRun_, context, request, response, std::move(f));
}

void ControlService::Stub::async::CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>* ControlService::Stub::PrepareAsyncCancelRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::evo::execution::v1::CancelRunResponse, ::evo::execution::v1::CancelRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>* ControlService::Stub::AsyncCancelRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlService::Stub::GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::evo::execution::v1::GetRunResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRun_, context, request, response);
}

void ControlService::Stub::async::GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, std::move(f));
}

void ControlService::Stub::async::GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRun_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>* ControlService::Stub::PrepareAsyncGetRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::evo::execution::v1::GetRunResponse, ::evo::execution::v1::GetRunRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRun_, context, request);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>* ControlService::Stub::AsyncGetRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRunRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlService::Stub::Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::evo::execution::v1::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Health_, context, request, response);
}

void ControlService::Stub::async::Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void ControlService::Stub::async::Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>* ControlService::Stub::PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::evo::execution::v1::HealthResponse, ::evo::execution::v1::HealthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Health_, context, request);
}

::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>* ControlService::Stub::AsyncHealthRaw(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

ControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlService::Service, ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::evo::execution::v1::SubmitRunRequest* req,
             ::evo::execution::v1::SubmitRunResponse* resp) {
               return service->SubmitRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlService::Service, ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::evo::execution::v1::CancelRunRequest* req,
             ::evo::execution::v1::CancelRunResponse* resp) {
               return service->CancelRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlService::Service, ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::evo::execution::v1::GetRunRequest* req,
             ::evo::execution::v1::GetRunResponse* resp) {
               return service->GetRun(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlService::Service, ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::evo::execution::v1::HealthRequest* req,
             ::evo::execution::v1::HealthResponse* resp) {
               return service->Health(ctx, req, resp);
             }, this)));
}

ControlService::Service::~Service() {
}

::grpc::Status ControlService::Service::SubmitRun(::grpc::ServerContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlService::Service::CancelRun(::grpc::ServerContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlService::Service::GetRun(::grpc::ServerContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlService::Service::Health(::grpc::ServerContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace evo
}  // namespace execution
}  // namespace v1
#include <grpcpp/ports_undef.inc>

