// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: evo/execution.proto
#ifndef GRPC_evo_2fexecution_2eproto__INCLUDED
#define GRPC_evo_2fexecution_2eproto__INCLUDED

#include "evo/execution.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace evo {
namespace execution {
namespace v1 {

// Control service. gRPC stubs generated in M17 (proto-gen-grpc-plugin not
// installed here). The message contracts above are usable independently of
// transport.
class ControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "evo.execution.v1.ControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::evo::execution::v1::SubmitRunResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::SubmitRunResponse>> AsyncSubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::SubmitRunResponse>>(AsyncSubmitRunRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::SubmitRunResponse>> PrepareAsyncSubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::SubmitRunResponse>>(PrepareAsyncSubmitRunRaw(context, request, cq));
    }
    virtual ::grpc::Status CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::evo::execution::v1::CancelRunResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::CancelRunResponse>> AsyncCancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::CancelRunResponse>>(AsyncCancelRunRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::CancelRunResponse>> PrepareAsyncCancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::CancelRunResponse>>(PrepareAsyncCancelRunRaw(context, request, cq));
    }
    virtual ::grpc::Status GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::evo::execution::v1::GetRunResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::GetRunResponse>> AsyncGetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::GetRunResponse>>(AsyncGetRunRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::GetRunResponse>> PrepareAsyncGetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::GetRunResponse>>(PrepareAsyncGetRunRaw(context, request, cq));
    }
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::evo::execution::v1::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::SubmitRunResponse>* AsyncSubmitRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::SubmitRunResponse>* PrepareAsyncSubmitRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::CancelRunResponse>* AsyncCancelRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::CancelRunResponse>* PrepareAsyncCancelRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::GetRunResponse>* AsyncGetRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::GetRunResponse>* PrepareAsyncGetRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::evo::execution::v1::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::evo::execution::v1::SubmitRunResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>> AsyncSubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>>(AsyncSubmitRunRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>> PrepareAsyncSubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>>(PrepareAsyncSubmitRunRaw(context, request, cq));
    }
    ::grpc::Status CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::evo::execution::v1::CancelRunResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>> AsyncCancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>>(AsyncCancelRunRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>> PrepareAsyncCancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>>(PrepareAsyncCancelRunRaw(context, request, cq));
    }
    ::grpc::Status GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::evo::execution::v1::GetRunResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>> AsyncGetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>>(AsyncGetRunRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>> PrepareAsyncGetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>>(PrepareAsyncGetRunRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::evo::execution::v1::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitRun(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response, std::function<void(::grpc::Status)>) override;
      void CancelRun(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRun(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>* AsyncSubmitRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::SubmitRunResponse>* PrepareAsyncSubmitRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::SubmitRunRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>* AsyncCancelRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::CancelRunResponse>* PrepareAsyncCancelRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::CancelRunRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>* AsyncGetRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::GetRunResponse>* PrepareAsyncGetRunRaw(::grpc::ClientContext* context, const ::evo::execution::v1::GetRunRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::evo::execution::v1::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::evo::execution::v1::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitRun_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelRun_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRun_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitRun(::grpc::ServerContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response);
    virtual ::grpc::Status CancelRun(::grpc::ServerContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response);
    virtual ::grpc::Status GetRun(::grpc::ServerContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response);
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitRun() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitRun(::grpc::ServerContext* context, ::evo::execution::v1::SubmitRunRequest* request, ::grpc::ServerAsyncResponseWriter< ::evo::execution::v1::SubmitRunResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelRun() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CancelRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelRun(::grpc::ServerContext* context, ::evo::execution::v1::CancelRunRequest* request, ::grpc::ServerAsyncResponseWriter< ::evo::execution::v1::CancelRunResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRun() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRun(::grpc::ServerContext* context, ::evo::execution::v1::GetRunRequest* request, ::grpc::ServerAsyncResponseWriter< ::evo::execution::v1::GetRunResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::evo::execution::v1::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::evo::execution::v1::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitRun<WithAsyncMethod_CancelRun<WithAsyncMethod_GetRun<WithAsyncMethod_Health<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SubmitRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitRun() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::evo::execution::v1::SubmitRunRequest* request, ::evo::execution::v1::SubmitRunResponse* response) { return this->SubmitRun(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitRun(
        ::grpc::MessageAllocator< ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitRun(
      ::grpc::CallbackServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CancelRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CancelRun() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::evo::execution::v1::CancelRunRequest* request, ::evo::execution::v1::CancelRunResponse* response) { return this->CancelRun(context, request, response); }));}
    void SetMessageAllocatorFor_CancelRun(
        ::grpc::MessageAllocator< ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CancelRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelRun(
      ::grpc::CallbackServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRun() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::evo::execution::v1::GetRunRequest* request, ::evo::execution::v1::GetRunResponse* response) { return this->GetRun(context, request, response); }));}
    void SetMessageAllocatorFor_GetRun(
        ::grpc::MessageAllocator< ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRun(
      ::grpc::CallbackServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Health() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::evo::execution::v1::HealthRequest* request, ::evo::execution::v1::HealthResponse* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::MessageAllocator< ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SubmitRun<WithCallbackMethod_CancelRun<WithCallbackMethod_GetRun<WithCallbackMethod_Health<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SubmitRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitRun() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelRun() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CancelRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRun() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitRun() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SubmitRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitRun(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelRun() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CancelRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelRun(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRun() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRun(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitRun() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitRun(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitRun(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CancelRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CancelRun() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelRun(context, request, response); }));
    }
    ~WithRawCallbackMethod_CancelRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelRun(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRun() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRun(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRun(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Health() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~WithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitRun() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::evo::execution::v1::SubmitRunRequest, ::evo::execution::v1::SubmitRunResponse>* streamer) {
                       return this->StreamedSubmitRun(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::SubmitRunRequest* /*request*/, ::evo::execution::v1::SubmitRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitRun(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::evo::execution::v1::SubmitRunRequest,::evo::execution::v1::SubmitRunResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelRun() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::evo::execution::v1::CancelRunRequest, ::evo::execution::v1::CancelRunResponse>* streamer) {
                       return this->StreamedCancelRun(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::CancelRunRequest* /*request*/, ::evo::execution::v1::CancelRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelRun(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::evo::execution::v1::CancelRunRequest,::evo::execution::v1::CancelRunResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRun : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRun() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::evo::execution::v1::GetRunRequest, ::evo::execution::v1::GetRunResponse>* streamer) {
                       return this->StreamedGetRun(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRun() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRun(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::GetRunRequest* /*request*/, ::evo::execution::v1::GetRunResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRun(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::evo::execution::v1::GetRunRequest,::evo::execution::v1::GetRunResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::evo::execution::v1::HealthRequest, ::evo::execution::v1::HealthResponse>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::evo::execution::v1::HealthRequest* /*request*/, ::evo::execution::v1::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::evo::execution::v1::HealthRequest,::evo::execution::v1::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitRun<WithStreamedUnaryMethod_CancelRun<WithStreamedUnaryMethod_GetRun<WithStreamedUnaryMethod_Health<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitRun<WithStreamedUnaryMethod_CancelRun<WithStreamedUnaryMethod_GetRun<WithStreamedUnaryMethod_Health<Service > > > > StreamedService;
};

}  // namespace v1
}  // namespace execution
}  // namespace evo


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_evo_2fexecution_2eproto__INCLUDED
